### ISSUE TITLE
to_yaml then parsing fails for specific use case

### ISSUE THREAD

**Issue by smojtabai** [ruby/psych#179]
I don't know any other way to help debug this but basically here is the marshal dump of the object (Ruby 1.9.3):

"\x04\bIC:\x15Enumerize::Value\"\ndaily\b:\x06EF:\n@attro:\x19Enumerize::Attribute\t:\v@klassc\x1AAdmin::InsertionOrder:\n@name:\x16frequency_capping:\f@values[\b@\x00IC;\x00\"\vweekly\b;\x06F;\a@\x06:\v@valueI\"\vweekly\x06;\x06FIC;\x00\"\fmonthly\b;\x06F;\a@\x06;\rI\"\fmonthly\x06;\x06F:\x10@value_hash{\bI\"\ndaily\x06;\x06F@\x00I\"\vweekly\x06;\x06F@\tI\"\fmonthly\x06;\x06F@\v;\rI\"\ndaily\x06;\x06F"

When I call to_yaml on this object I get: 

```
--- &70293058189420 !ruby/string:Enumerize::Value
str: daily
attr: &70293057862200 !ruby/object:Enumerize::Attribute
  klass: !ruby/class 'Admin::InsertionOrder'
  name: :frequency_capping
  values:
  - *70293058189420
  - &70293058189240 !ruby/string:Enumerize::Value
    str: weekly
    attr: *70293057862200
    value: weekly
  - &70293058188780 !ruby/string:Enumerize::Value
    str: monthly
    attr: *70293057862200
    value: monthly
  value_hash:
    daily: *70293058189420
    weekly: *70293058189240
    monthly: *70293058188780
value: daily
```

Then when I try to YAML.load this happens:

Psych::BadAlias: Unknown alias: 70293058189420
    from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:246:in `block in visit_Psych_Nodes_Alias'
