### ISSUE TITLE
wrong line reported in 'did not find expected key while parsing a block mapping'

### ISSUE THREAD

**Issue by djellemah** [ruby/psych#190]
When parsing this yaml

```
key_one:
  inner:
  - value1
  - value2

key_two:
    inner:
  - value1
  - value2
```

the error message

```
Psych::SyntaxError: (/tmp/oops.yaml): did not find expected key while parsing a block mapping at line 1 column 1
```

contains the wrong line number. It should be reporting line 7 column 5.

**Comment by happycollision** [comment]
Super glad I found this issue. Probably saved my an hour of hair pulling. In my case, it seems to be reporting the correct column number, but still reports line 1 incorrectly.

**Comment by illepic** [comment]
To anyone stumbling through the internet that finds this issue for related reasons: Somewhere in your YAML you have extra spaces (or not enough spaces) before a key value. Thank you all for helping me solve this on a completely different project!

**Comment by DaveCollinsJr** [comment]
+1 on the empty space in the yml file.  Copy/paste error.

**Comment by philix** [comment]
@illepic Thank you so much! I was missing an extra space.

**Comment by rohstar** [comment]
thanks @illepic!

**Comment by cleverington** [comment]
Thanks @illepic!

**Comment by Gimcrack** [comment]
Found my syntax error. Thanks! @illepic

**Comment by MrWilhelm** [comment]
For anyone who is looking for this stupid error, I fix error by removing " ' " character.

**Comment by sanguis** [comment]
so it was a bad copy for me.

In vim I did a search of `^\(\s\s\)\+` to find all instances of good spacing and was able to find my bug

**Comment by dangan249** [comment]
+1

**Comment by aurawindsurfing** [comment]
209:11 should have beed 209:09 ... cheers for pointing that out!

**Comment by ryanooi** [comment]
Please check spacing. i got the same error because additional spacing.

**Comment by pooja-mane** [comment]
Hi I also got this error as
"did not find expected key while parsing a block mapping at line 3 column 5"
My code is as follow
create_list: "Create a List"
  message: "Save Profiles"
but when I place a message key in another key it works fine.
plz tell me if any one knows solution...
I have checked spacing also, as there is no extra spacing in line.
Thank you...

**Comment by elcortez** [comment]
@pooja-mane Can you try something: 
- delete the lines where the problem seems to happens
- check that you can launch your server after deleting (if so, you have spotted where are the 'wrong' lines)
- rewrite them by hand
- be careful with "'" and '"' : use " mostly if possible
- I had this issue after bulk changing all my " to '; and then there was a "If you didn"t request" so you see my mistake was very small indeed ^^

**Comment by pooja-mane** [comment]
@elcortez thank you.
I got my mistake in code.
create_list: "Create a List"
   message: "Save Profiles"
as I was using massage key as create_list.message which is wrong.
as when it searches for for create_list it got a label "Create a List" it wont go to search for message key.
I changed my code as
create_list:
  message: "Save Profiles"

**Comment by einverne** [comment]
Save me a lot of time. And here is a yamllint tool. http://www.yamllint.com/

**Comment by joney000** [comment]
+1

**Comment by mahemoff** [comment]
Here's command-line yamllint. It gives the correct line number.

https://github.com/adrienverge/yamllint

**Comment by ORESoftware** [comment]
SPACES AS SYNTAX IS THE DUMBEST THING EVER, thank you

**Comment by philix** [comment]
@ORESoftware that's the whole point of using YAML. Use JSON instead.

**Comment by BrizzleRocker** [comment]
> Here's command-line yamllint. It gives the correct line number.

https://github.com/adrienverge/yamllint

Thank you @mahemoff, you just saved me a world of pain!

**Comment by vfonic** [comment]
Ended up here after missing a closing `'` sign.

Let's assume `paths:` is at line 1.

The error message was:
`did not find expected key while parsing a block mapping at line 5 column 3 (Psych::SyntaxError)`

While the actual error is at line 20.

```yaml
paths:
  # customer:
  #   path: /news/entertainment-arts-27221191
  # before_capture: 'javascript/interact--casper.js' # (optional) JavaScript file to execute before taking the screenshot of this path.
  customers_login:                '/account/login'
  customers_register:             '/account/register'
  404:                            '/wraith_testing'
  article_konfigurator:           '/blogs/blog/alte-brillen-neu-verglasen'
  article:                        '/blogs/blog/warum-werden-brillenglaeser-entspiegelt'
  article_lexikon:                        '/blogs/lexikon/basis' # blog lexikon article
  blog_lexikon:                   '/blogs/lexikon' # blog index
  blog_lexikon_tag:                   '/blogs/lexikon/tagged/b' # blog lexikon tag
  blog:                           '/blogs/blog'
  cart:                           '/cart'
  index:                          '/'
  page_about_us:                  '/pages/uber-topglas'
  page_composer_einstarkenglaser: '/pages/einstarkenglaser'
  page_composer_gleitsichtglaser: '/pages/gleitsichtglaeser'
  page_composer_koln:             '/pages/optiker-koeln'
  page_consulting:                '/pages/unsere-brillenglaser-im-detail # HERE'S THE ERROR
  page_contact:                   '/pages/kontakt'
  page_faq:                       '/pages/haeufige-fragen'
  page_functioniert:              '/pages/so-funktionierts'
  page_konfigurator:              '/pages/brillenglaeser-online-auswaehlen'
  page:                           '/pages/lieferzeiten'
  search:                         '/search'
  search:                         '/search?type=article,page&q=sehstarke'
```

**Comment by juanmirocks** [comment]
Do not write colons within strings as in:

```yaml
- printf 'commit:'`
```

**Comment by goalaleo** [comment]
For me the line number was incorrect when I had unescaped double quotes inside a translation...

**Comment by farfromunique** [comment]
Copy/pasting code from the internet can have WEIRD results. I had to re-write an entire file to fix this issue; my spaces and quotes were right, but there were invisible whitespace characters hidden... somewhere.

**Comment by emfluenceindia** [comment]
This vagrant error reporting must be looked into! For me reported line number was 74, while it was 84 actually. For beginners like me its a nightmare to understand what's went wrong! It was no copy/paste for me... I forgot to enable the key called `plugins` while I have user-switching added under it! :) Glad that I could find it out quickly.

**Comment by Freyert** [comment]
1. [parsing begins](https://github.com/ruby/psych/blob/6333cf8cc365b644fbffd8b122f2e720f5654e77/lib/psych.rb#L401)
2. [parser constructor](https://github.com/ruby/psych/blob/6333cf8cc365b644fbffd8b122f2e720f5654e77/lib/psych/parser.rb#L47-L49)
3. [Handler Abstract Class](https://github.com/ruby/psych/blob/6333cf8cc365b644fbffd8b122f2e720f5654e77/lib/psych/handler.rb)
   + Handles events on the parse stream.
   + [`Handler#event_location`](https://github.com/ruby/psych/blob/6333cf8cc365b644fbffd8b122f2e720f5654e77/lib/psych/handler.rb#L246) : my money's on this guy.

**Comment by Freyert** [comment]
It seems like this is manifesting itself in a variety of ways:

1. [colon within string](https://github.com/ruby/psych/issues/190#issuecomment-294355216)
2. [unescaped double quotes within a value](https://github.com/ruby/psych/issues/190#issuecomment-303358082)

**Comment by WaKeMaTTa** [comment]
When this happens to me i use this tool it give you the correct line:

https://yamlchecker.com/

**Comment by jmervine** [comment]
I saw this issue ("line 1, column 1") do to a comma at the end of the line after converting json by hand.

E.g.
```
foo:
- "bar bah",
- "asdf asdf"
```

**Comment by mrbrant89** [comment]
Just had this issue too. It indicated that the error was on line 2, column 1. But it was on line 13 (extra quote). Thanks for the tip, I'm not crazy, there really was an error in there 👍

**Comment by OkThought** [comment]
Had the same issue, but instead of wrong whitespaces I got comments inside a single command like the following:

```
  script:
    - if true; then
         # comment
         echo hello;
      fi
```

The `travis lint` reported error on line 2, column 1 or on line 1, column 1 during my experiments. While error was on some 23 line :\
I'm glad I solved this puzzle :)

**Comment by OmariGrant** [comment]
Had the same issue on Windows 10 today. 
I used https://yamlchecker.com/ as recommended by @WaKeMaTTa 

Resolution:
No double quotes needed for Windows directory.

**Comment by Saket-Kr** [comment]
I had double 'double quotes' in one of my stories. removing that solved the problem.

**Comment by patricknelson** [comment]
Also:  [**Zero width space characters**](https://stackoverflow.com/questions/2973698/whats-html-character-code-8203)  (`&#8203;`)

I had the same issue after copying/pasting a YAML config from a web page into my IDE and couldn't figure out why it worked fine when I typed it but not when I pasted the contents. In my case, it was loads of nefarious **zero width space characters** embedded randomly in my copied text which were completely invisible. I didn't realize it until I wrote a little JavaScript loop to iterate over every character in a suspicious string passed into [yamllint.com](http://www.yamllint.com/) until I found something that was off:

```js
// Copied from very first line of: http://bbc-news.github.io/wraith/configs.html
const string = '​#Headless browser option​';
let output = '';
for(var i = 0; i < string.length; i++) {
	output += '\'' + string.charAt(i) + '\'' + ' (' + string.charCodeAt(i) +  ') ';
}

// Outputs: '​' (8203) '#' (35) 'H' (72) 'e' (101) 'a' ... etc
console.log(output);
```

Bingo: **8203**

You can't even see it in the code above, but it's still there (try it yourself). Once I figured that out, I was able to create a quick script to remove all characters in my YAML config which were outside of my expected character code range and suddenly it started parsing properly.

**Comment by AdiedX** [comment]
Specifically, I got a `yaml did not find expected ',' or ']'` error. It wasn't a spacing issue for me:

Original yaml block:
```yaml
routes:
  - name: api-admin-private
    apply_to: api-admin
    config:
      hosts: [${POD_NAMESPACE}api-admin.${DOMAIN_NAME}]
```

The string with environment variables needed to be within quotes in the hosts array:
```yaml
routes:
  - name: api-admin-private
    apply_to: api-admin
    config:
      hosts: ['${POD_NAMESPACE}api-admin.${DOMAIN_NAME}']
```

**Comment by TravisHi** [comment]
Just had this when trying to set up a project via homestead. In my case I had incorrectly indented `- map: project.test`

**Comment by xofred** [comment]
In my case was extra comma instead of extra/ lack of whitespace😂
```yml
  node:
    ip: '127.0.0.1',
    port: 7001
```
