### ISSUE TITLE
Using mapping nodes in merge key causes bad load

### ISSUE THREAD

**Issue by connec** [ruby/psych#202]
``` yaml
map:
  <<:
    hello: world
```

This loads as:

``` json
{
  "map": {
    "<<": { "hello": "world" }
  }
}
```

It _should_ load as:

``` json
{
  "map": { "hello": "world" }
}
```
