### ISSUE TITLE
issue parsing anchors with mid-level API

### ISSUE THREAD

**Issue by akostadinov** [ruby/psych#314]
I am seeing a problem with anchors when using the mid-level API.

tt.yaml:
```yaml
action1:
  element:
    selector:
      xpath: &some_name |
               asdfghj
action2:
  element:
    xpath: *some_name
```

Parsing:
```ruby
pry> Psych.parse_file("/tmp/tt.yml").root.children.each(&:transform)
Psych::BadAlias: Unknown alias: some_name
from /usr/share/ruby/psych/visitors/to_ruby.rb:319:in `block in visit_Psych_Nodes_Alias'
```

**Comment by araslanov-e** [comment]
:+1:

**Comment by tenderlove** [comment]
Sorry, I don't think this case can be supported.  The sample code provided is iterating each child of the root node, and asking that node to transform itself in to Ruby.  Essentially you are splitting the larger tree in to two smaller trees, then converting each tree to Ruby.  So this tree

```
action1:
  element:
    selector:
      xpath: &some_name |
               asdfghj
```

Has no idea about this tree:

```
action2:
  element:
    xpath: *some_name
```
