### ISSUE TITLE
is there a way to force double quoted value output?

### ISSUE THREAD

**Issue by coldnebo** [ruby/psych#322]
If I `YAML.load` the following data:
```
---
        en:
          case1: Here is a string with a "double quoted part" inside of it.
          case2: "Here is a string with double quotes around it."
          case3: 'Here is a string with single quotes around it and "double quoted part" inside of it.'
          case4: Here is a string with \"escaped double quoted part\" and no surrounding quotes.
          case5: "Here is a double quoted string with \"escaped parts\"."
          case6: Here is a plain string.
          case7: Here is a string with a 'single quoted part' in it.
          case8: |
            Here is a multiline string
            broken across several lines
            that should be one line and 
            double quoted.
          case9: Here is a string with a "double quoted part at the end"
```

I would like to `YAML.dump( some_flag: true, line_width: -1 )` the following data:
```
---
        en:
          case1: "Here is a string with a \"double quoted part\" inside of it."
          case2: "Here is a string with double quotes around it."
          case3: "Here is a string with single quotes around it and \"double quoted part\" inside of it."
          case4: "Here is a string with \"escaped double quoted part\" and no surrounding quotes."
          case5: "Here is a double quoted string with \"escaped parts\"."
          case6: "Here is a plain string."
          case7: "Here is a string with a 'single quoted part' in it."
          case8: "Here is a multiline string broken across several lines that should be one line and double quoted."
          case9: "Here is a string with a \"double quoted part at the end\""
```

Is there a way to do this with YAML.dump?  It seems to convert data in an unpredictable way in the above cases.

If I had to summarize the high-level requirement we are getting from our translators and the tools they use, they want all the values to be double-quoted.

In trying to search for answers to this issue, I came across some hacks on StackOverflow, and several of them said it couldn't be done.  But one said something about custom Psych emitters?  I had trouble finding more information on those.

More background:

The obvious answer might be: go through and change your original YAML to use double quoted strings.  However given our process, this may be time-consuming and error-prone, so before we do a large-scale project to update all the values, I wanted to investigate the possibility of a code solution... making some kind of 'lint' rake task or the like to convert and sanitize our YAML into a standard format for our translators.
