### ISSUE TITLE
Psych.load   IOError: uninitialized stream

### ISSUE THREAD

**Issue by plusor** [ruby/psych#327]
```ruby
Raven.delay.capture_message('feedback', params) # IOError: uninitialized stream
```

## params

```yaml
--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
file: !ruby/object:ActionDispatch::Http::UploadedFile
  tempfile: !ruby/marshalable:Tempfile
    :__v2__:
    - :@unlinked
    - :@mode
    - :@tmpfile
    - :@opts
    ? - false
      - 2562
      - &1 !ruby/object:File {}
      - :perm: 384
    : *1
  original_filename: favicon.ico
  content_type: application/octet-stream
  headers: "Content-Disposition: form-data; name=\"file\"; filename=\"favicon.ico\"\r\nContent-Type:
    application/octet-stream\r\n"
controller: feedback
action: create
```

### Simplified version

```ruby
YAML.load({ attachment: Tempfile.new }.to_yaml)  # IOError: uninitialized stream
```
