### ISSUE TITLE
Psych.dump convert emoji characters into unicode

### ISSUE THREAD

**Issue by neumayr** [ruby/psych#371]
Hey!  🙌 

The origin of this issue is [`i18n-tasks`](https://github.com/glebm/i18n-tasks) which [delegates](https://github.com/glebm/i18n-tasks/issues/291#issuecomment-414433435) YAML dumping to this library.

> I've spotted that `i18n-tasks normalize` converts emoji characters into unicode which makes them much harder to read and change afterward. IMHO, this should be necessary because `yaml` is capable to understand plain emoji chars. What do you think about this one?

##### Before
```yml
lang:
  de-de: 🇩🇪 German
  en-uk: 🇺🇸 English
  header: 🌐 Select Language
```

##### After `i18n-tasks normalize` / `Psych.dump` 
```
lang:
  de-de: "\U0001F1E9\U0001F1EA German"
  en-uk: "\U0001F1FA\U0001F1F8 English"
  header: "\U0001F310 Select Language"
```

#### Converter tool
* https://r12a.github.io/app-conversion/

✨ Please let emojis live in `yaml` files. 💙 💚 💛 💜

---

**Note** This issue was moved from https://github.com/glebm/i18n-tasks/issues/291
