### ISSUE TITLE
Multiline folded blocks with greater than symbol >

### ISSUE THREAD

**Issue by Matt-Yorkley** [ruby/psych#466]
Is it just me, or is handling of multiline blocks is really broken?

- Folded blocks with `|` are fine :heavy_check_mark: 
- Folded blocks with `>` are always broken :x: 
- Folded blocks with `>+` are always broken :x: 
- Folded blocks with `>-` are fine :heavy_check_mark: 

If I load this `input.yml` file with `Psych#load_file`:

```yaml
# input.yml
---
example1:
  pipe: |
    This is a multiline
    folded block.
  greaterthan: >
    This is a multiline
    folded block as well.
  greaterthanplus: >+
    This is a another multiline
    folded block.
  greaterthanminus: >-
    This is a another multiline
    folded block.
example2:
  pipe: |
    This is a 'multiline'
    folded block.
  greaterthan: >
    This is a 'multiline'
    folded block as well.
  greaterthanplus: >+
    This is a another 'multiline'
    folded block.
  greaterthanminus: >-
    This is a another 'multiline'
    folded block.
```

and then write it to `output.yml` with `Psych#dump`, I get this:

```yaml
# output.yml
---
example1:
  pipe: |
    This is a multiline
    folded block.
  greaterthan: 'This is a multiline folded block as well.

    '
  greaterthanplus: 'This is a another multiline folded block.

    '
  greaterthanminus: This is a another multiline folded block.
example2:
  pipe: |
    This is a 'multiline'
    folded block.
  greaterthan: 'This is a ''multiline'' folded block as well.

    '
  greaterthanplus: 'This is a another ''multiline'' folded block.

    '
  greaterthanminus: This is a another 'multiline' folded block.
```

**Comment by perlpunk** [comment]
I want to comment on the terminology, as I think using the correct names makes it easier to understand the spec/docs.

> * Folded blocks with `|` are fine

There are two types of block scalars, literal `|` and folded `>`. (The `>` is mnemonic for a folded `|`.)
The literal style keeps all linebreaks, spaces and tabs. The folded style folds the lines with spaces.
May I refer you to [my article about quoting in YAML](https://www.yaml.info/learn/quote.html#block)?

The problem is that the YAML dumper has to figure out the best way to dump a string (if it is not able to preserve the style from loading).
This is not trivial, and depending on the use case / content of the string there can be different answers.
Also the rules for the folded block scalar are more complicated than it might seem, so I understand that a YAML processor avoids using this style.

But I think that a string with exactly one linebreak at the end should be dumped as a literal block scalar or with double quotes, instead of single quotes:
```
double: "string\n"
literal: |
  string
```
As soon as the string has two lines, psych chooses `|`, so maybe this can be improved for one line, too.
It should take care of strings with only empty lines, though, where double quotes, e.g. `"\n\n\n"`, are better than literal style.

**Comment by Matt-Yorkley** [comment]
```yaml
# input.yml
---
example:
  greaterthan: >
    Single-line string written
    on multiple lines.
```

```ruby
hash = Psych.load_file('input.yml')
puts hash['example']['greaterthan']
#=> "Single-line string defined on multiple lines.\n"
File.open(output, "w") { |file| Psych.dump(hash, file)
```
I'm not sure the trailing newline should be here at all? It's a single-line string :point_up: 

```yaml
# output.yml
---
example:
  greaterthan: 'Single-line string defined on multiple lines.
   
    '
```
Double newlines should definitely not be here :point_up:
