### ISSUE TITLE
deep merging

### ISSUE THREAD

**Issue by brewster1134** [ruby/psych#62]
i noticed you cannot deep merge keys.

```
defaults: &defaults
  parent:
    nested_one: foo
    nested_two: bar

development:
  <<: *defaults
  parent:
    nested_one: bar
```

returns:

```
defaults:
  parent:
    nested_one: foo
    nested_two: bar
development:
  parent:
    nested_one: bar
```

but i was expecting:

```
defaults:
  parent:
    nested_one: foo
    nested_two: bar
development:
  parent:
    nested_one: bar
    nested_two: bar       # this key would exist in a proper deep merge
```

the yaml specs dont really cover how it is should work, but is there a deep merging solution? if it should deep merge, i can update the psych test specs.
